[package]
name = "oz-core"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = { version = "1.8.2", default-features = false, features = ["pure"] }
borsh = {version = "1.5.7", default-features = false, features = ["derive"]}
thiserror = { version = "2.0.12", default-features = false }
